/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClareamentoDentalRouteImport } from './routes/clareamento-dental'
import { Route as CrcRouteImport } from './routes/crc'
import { Route as CrcInstitucionalRouteImport } from './routes/crc-institucional'
import { Route as ImplanteDentarioRouteImport } from './routes/implante-dentario'
import { Route as LimpezaDentalRouteImport } from './routes/limpeza-dental'
import { Route as OdontopediatriaRouteImport } from './routes/odontopediatria'
import { Route as OrtodontiaRouteImport } from './routes/ortodontia'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ProteseDentariaRouteImport } from './routes/protese-dentaria'
import { Route as RestauracaoDentariaRouteImport } from './routes/restauracao-dentaria'
import { Route as RhRouteImport } from './routes/rh'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as CarreirasIndexRouteImport } from './routes/carreiras/index'
import { Route as CarreirasSlugRouteImport } from './routes/carreiras/$slug'
import { Route as TratamentosSlugRouteImport } from './routes/tratamentos/$slug'
import { Route as ApiCrcInstalarRouteImport } from './routes/api/crc/instalar'
import { Route as ApiCrcLeadRouteImport } from './routes/api/crc/lead'
import { Route as ApiCrcMcpRouteImport } from './routes/api/crc/mcp'
import { Route as ApiCrcMotorRouteImport } from './routes/api/crc/motor'
import { Route as ApiCrcSaudeRouteImport } from './routes/api/crc/saude'
import { Route as ApiCrcWhatsappRouteImport } from './routes/api/crc/whatsapp'
import { Route as ApiRhVarrerRouteImport } from './routes/api/rh/varrer'
import { Route as ApiRhCurriculoIdRouteImport } from './routes/api/rh/curriculo/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClareamentoDentalRoute = ClareamentoDentalRouteImport.update({
  id: '/clareamento-dental',
  path: '/clareamento-dental',
  getParentRoute: () => rootRouteImport,
} as any)
const CrcRoute = CrcRouteImport.update({
  id: '/crc',
  path: '/crc',
  getParentRoute: () => rootRouteImport,
} as any)
const CrcInstitucionalRoute = CrcInstitucionalRouteImport.update({
  id: '/crc-institucional',
  path: '/crc-institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplanteDentarioRoute = ImplanteDentarioRouteImport.update({
  id: '/implante-dentario',
  path: '/implante-dentario',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezaDentalRoute = LimpezaDentalRouteImport.update({
  id: '/limpeza-dental',
  path: '/limpeza-dental',
  getParentRoute: () => rootRouteImport,
} as any)
const OdontopediatriaRoute = OdontopediatriaRouteImport.update({
  id: '/odontopediatria',
  path: '/odontopediatria',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtodontiaRoute = OrtodontiaRouteImport.update({
  id: '/ortodontia',
  path: '/ortodontia',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteseDentariaRoute = ProteseDentariaRouteImport.update({
  id: '/protese-dentaria',
  path: '/protese-dentaria',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauracaoDentariaRoute = RestauracaoDentariaRouteImport.update({
  id: '/restauracao-dentaria',
  path: '/restauracao-dentaria',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasIndexRoute = CarreirasIndexRouteImport.update({
  id: '/carreiras/',
  path: '/carreiras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasSlugRoute = CarreirasSlugRouteImport.update({
  id: '/carreiras/$slug',
  path: '/carreiras/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosSlugRoute = TratamentosSlugRouteImport.update({
  id: '/tratamentos/$slug',
  path: '/tratamentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrcInstalarRoute = ApiCrcInstalarRouteImport.update({
  id: '/api/crc/instalar',
  path: '/api/crc/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrcLeadRoute = ApiCrcLeadRouteImport.update({
  id: '/api/crc/lead',
  path: '/api/crc/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrcMcpRoute = ApiCrcMcpRouteImport.update({
  id: '/api/crc/mcp',
  path: '/api/crc/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrcMotorRoute = ApiCrcMotorRouteImport.update({
  id: '/api/crc/motor',
  path: '/api/crc/motor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrcSaudeRoute = ApiCrcSaudeRouteImport.update({
  id: '/api/crc/saude',
  path: '/api/crc/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrcWhatsappRoute = ApiCrcWhatsappRouteImport.update({
  id: '/api/crc/whatsapp',
  path: '/api/crc/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRhVarrerRoute = ApiRhVarrerRouteImport.update({
  id: '/api/rh/varrer',
  path: '/api/rh/varrer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRhCurriculoIdRoute = ApiRhCurriculoIdRouteImport.update({
  id: '/api/rh/curriculo/$id',
  path: '/api/rh/curriculo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clareamento-dental': typeof ClareamentoDentalRoute
  '/crc': typeof CrcRoute
  '/crc-institucional': typeof CrcInstitucionalRoute
  '/implante-dentario': typeof ImplanteDentarioRoute
  '/limpeza-dental': typeof LimpezaDentalRoute
  '/odontopediatria': typeof OdontopediatriaRoute
  '/ortodontia': typeof OrtodontiaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/protese-dentaria': typeof ProteseDentariaRoute
  '/restauracao-dentaria': typeof RestauracaoDentariaRoute
  '/rh': typeof RhRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/carreiras/$slug': typeof CarreirasSlugRoute
  '/tratamentos/$slug': typeof TratamentosSlugRoute
  '/carreiras/': typeof CarreirasIndexRoute
  '/api/crc/instalar': typeof ApiCrcInstalarRoute
  '/api/crc/lead': typeof ApiCrcLeadRoute
  '/api/crc/mcp': typeof ApiCrcMcpRoute
  '/api/crc/motor': typeof ApiCrcMotorRoute
  '/api/crc/saude': typeof ApiCrcSaudeRoute
  '/api/crc/whatsapp': typeof ApiCrcWhatsappRoute
  '/api/rh/varrer': typeof ApiRhVarrerRoute
  '/api/rh/curriculo/$id': typeof ApiRhCurriculoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clareamento-dental': typeof ClareamentoDentalRoute
  '/crc': typeof CrcRoute
  '/crc-institucional': typeof CrcInstitucionalRoute
  '/implante-dentario': typeof ImplanteDentarioRoute
  '/limpeza-dental': typeof LimpezaDentalRoute
  '/odontopediatria': typeof OdontopediatriaRoute
  '/ortodontia': typeof OrtodontiaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/protese-dentaria': typeof ProteseDentariaRoute
  '/restauracao-dentaria': typeof RestauracaoDentariaRoute
  '/rh': typeof RhRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/carreiras/$slug': typeof CarreirasSlugRoute
  '/tratamentos/$slug': typeof TratamentosSlugRoute
  '/carreiras': typeof CarreirasIndexRoute
  '/api/crc/instalar': typeof ApiCrcInstalarRoute
  '/api/crc/lead': typeof ApiCrcLeadRoute
  '/api/crc/mcp': typeof ApiCrcMcpRoute
  '/api/crc/motor': typeof ApiCrcMotorRoute
  '/api/crc/saude': typeof ApiCrcSaudeRoute
  '/api/crc/whatsapp': typeof ApiCrcWhatsappRoute
  '/api/rh/varrer': typeof ApiRhVarrerRoute
  '/api/rh/curriculo/$id': typeof ApiRhCurriculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clareamento-dental': typeof ClareamentoDentalRoute
  '/crc': typeof CrcRoute
  '/crc-institucional': typeof CrcInstitucionalRoute
  '/implante-dentario': typeof ImplanteDentarioRoute
  '/limpeza-dental': typeof LimpezaDentalRoute
  '/odontopediatria': typeof OdontopediatriaRoute
  '/ortodontia': typeof OrtodontiaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/protese-dentaria': typeof ProteseDentariaRoute
  '/restauracao-dentaria': typeof RestauracaoDentariaRoute
  '/rh': typeof RhRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/carreiras/$slug': typeof CarreirasSlugRoute
  '/tratamentos/$slug': typeof TratamentosSlugRoute
  '/carreiras/': typeof CarreirasIndexRoute
  '/api/crc/instalar': typeof ApiCrcInstalarRoute
  '/api/crc/lead': typeof ApiCrcLeadRoute
  '/api/crc/mcp': typeof ApiCrcMcpRoute
  '/api/crc/motor': typeof ApiCrcMotorRoute
  '/api/crc/saude': typeof ApiCrcSaudeRoute
  '/api/crc/whatsapp': typeof ApiCrcWhatsappRoute
  '/api/rh/varrer': typeof ApiRhVarrerRoute
  '/api/rh/curriculo/$id': typeof ApiRhCurriculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clareamento-dental'
    | '/crc'
    | '/crc-institucional'
    | '/implante-dentario'
    | '/limpeza-dental'
    | '/odontopediatria'
    | '/ortodontia'
    | '/politica-de-privacidade'
    | '/protese-dentaria'
    | '/restauracao-dentaria'
    | '/rh'
    | '/trabalhe-conosco'
    | '/carreiras/$slug'
    | '/tratamentos/$slug'
    | '/carreiras/'
    | '/api/crc/instalar'
    | '/api/crc/lead'
    | '/api/crc/mcp'
    | '/api/crc/motor'
    | '/api/crc/saude'
    | '/api/crc/whatsapp'
    | '/api/rh/varrer'
    | '/api/rh/curriculo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clareamento-dental'
    | '/crc'
    | '/crc-institucional'
    | '/implante-dentario'
    | '/limpeza-dental'
    | '/odontopediatria'
    | '/ortodontia'
    | '/politica-de-privacidade'
    | '/protese-dentaria'
    | '/restauracao-dentaria'
    | '/rh'
    | '/trabalhe-conosco'
    | '/carreiras/$slug'
    | '/tratamentos/$slug'
    | '/carreiras'
    | '/api/crc/instalar'
    | '/api/crc/lead'
    | '/api/crc/mcp'
    | '/api/crc/motor'
    | '/api/crc/saude'
    | '/api/crc/whatsapp'
    | '/api/rh/varrer'
    | '/api/rh/curriculo/$id'
  id:
    | '__root__'
    | '/'
    | '/clareamento-dental'
    | '/crc'
    | '/crc-institucional'
    | '/implante-dentario'
    | '/limpeza-dental'
    | '/odontopediatria'
    | '/ortodontia'
    | '/politica-de-privacidade'
    | '/protese-dentaria'
    | '/restauracao-dentaria'
    | '/rh'
    | '/trabalhe-conosco'
    | '/carreiras/$slug'
    | '/tratamentos/$slug'
    | '/carreiras/'
    | '/api/crc/instalar'
    | '/api/crc/lead'
    | '/api/crc/mcp'
    | '/api/crc/motor'
    | '/api/crc/saude'
    | '/api/crc/whatsapp'
    | '/api/rh/varrer'
    | '/api/rh/curriculo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClareamentoDentalRoute: typeof ClareamentoDentalRoute
  CrcRoute: typeof CrcRoute
  CrcInstitucionalRoute: typeof CrcInstitucionalRoute
  ImplanteDentarioRoute: typeof ImplanteDentarioRoute
  LimpezaDentalRoute: typeof LimpezaDentalRoute
  OdontopediatriaRoute: typeof OdontopediatriaRoute
  OrtodontiaRoute: typeof OrtodontiaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ProteseDentariaRoute: typeof ProteseDentariaRoute
  RestauracaoDentariaRoute: typeof RestauracaoDentariaRoute
  RhRoute: typeof RhRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
  CarreirasSlugRoute: typeof CarreirasSlugRoute
  TratamentosSlugRoute: typeof TratamentosSlugRoute
  CarreirasIndexRoute: typeof CarreirasIndexRoute
  ApiCrcInstalarRoute: typeof ApiCrcInstalarRoute
  ApiCrcLeadRoute: typeof ApiCrcLeadRoute
  ApiCrcMcpRoute: typeof ApiCrcMcpRoute
  ApiCrcMotorRoute: typeof ApiCrcMotorRoute
  ApiCrcSaudeRoute: typeof ApiCrcSaudeRoute
  ApiCrcWhatsappRoute: typeof ApiCrcWhatsappRoute
  ApiRhVarrerRoute: typeof ApiRhVarrerRoute
  ApiRhCurriculoIdRoute: typeof ApiRhCurriculoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clareamento-dental': {
      id: '/clareamento-dental'
      path: '/clareamento-dental'
      fullPath: '/clareamento-dental'
      preLoaderRoute: typeof ClareamentoDentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crc': {
      id: '/crc'
      path: '/crc'
      fullPath: '/crc'
      preLoaderRoute: typeof CrcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crc-institucional': {
      id: '/crc-institucional'
      path: '/crc-institucional'
      fullPath: '/crc-institucional'
      preLoaderRoute: typeof CrcInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implante-dentario': {
      id: '/implante-dentario'
      path: '/implante-dentario'
      fullPath: '/implante-dentario'
      preLoaderRoute: typeof ImplanteDentarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpeza-dental': {
      id: '/limpeza-dental'
      path: '/limpeza-dental'
      fullPath: '/limpeza-dental'
      preLoaderRoute: typeof LimpezaDentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odontopediatria': {
      id: '/odontopediatria'
      path: '/odontopediatria'
      fullPath: '/odontopediatria'
      preLoaderRoute: typeof OdontopediatriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortodontia': {
      id: '/ortodontia'
      path: '/ortodontia'
      fullPath: '/ortodontia'
      preLoaderRoute: typeof OrtodontiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protese-dentaria': {
      id: '/protese-dentaria'
      path: '/protese-dentaria'
      fullPath: '/protese-dentaria'
      preLoaderRoute: typeof ProteseDentariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restauracao-dentaria': {
      id: '/restauracao-dentaria'
      path: '/restauracao-dentaria'
      fullPath: '/restauracao-dentaria'
      preLoaderRoute: typeof RestauracaoDentariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras/': {
      id: '/carreiras/'
      path: '/carreiras'
      fullPath: '/carreiras/'
      preLoaderRoute: typeof CarreirasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras/$slug': {
      id: '/carreiras/$slug'
      path: '/carreiras/$slug'
      fullPath: '/carreiras/$slug'
      preLoaderRoute: typeof CarreirasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos/$slug': {
      id: '/tratamentos/$slug'
      path: '/tratamentos/$slug'
      fullPath: '/tratamentos/$slug'
      preLoaderRoute: typeof TratamentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crc/instalar': {
      id: '/api/crc/instalar'
      path: '/api/crc/instalar'
      fullPath: '/api/crc/instalar'
      preLoaderRoute: typeof ApiCrcInstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crc/lead': {
      id: '/api/crc/lead'
      path: '/api/crc/lead'
      fullPath: '/api/crc/lead'
      preLoaderRoute: typeof ApiCrcLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crc/mcp': {
      id: '/api/crc/mcp'
      path: '/api/crc/mcp'
      fullPath: '/api/crc/mcp'
      preLoaderRoute: typeof ApiCrcMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crc/motor': {
      id: '/api/crc/motor'
      path: '/api/crc/motor'
      fullPath: '/api/crc/motor'
      preLoaderRoute: typeof ApiCrcMotorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crc/saude': {
      id: '/api/crc/saude'
      path: '/api/crc/saude'
      fullPath: '/api/crc/saude'
      preLoaderRoute: typeof ApiCrcSaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crc/whatsapp': {
      id: '/api/crc/whatsapp'
      path: '/api/crc/whatsapp'
      fullPath: '/api/crc/whatsapp'
      preLoaderRoute: typeof ApiCrcWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rh/varrer': {
      id: '/api/rh/varrer'
      path: '/api/rh/varrer'
      fullPath: '/api/rh/varrer'
      preLoaderRoute: typeof ApiRhVarrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rh/curriculo/$id': {
      id: '/api/rh/curriculo/$id'
      path: '/api/rh/curriculo/$id'
      fullPath: '/api/rh/curriculo/$id'
      preLoaderRoute: typeof ApiRhCurriculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClareamentoDentalRoute: ClareamentoDentalRoute,
  CrcRoute: CrcRoute,
  CrcInstitucionalRoute: CrcInstitucionalRoute,
  ImplanteDentarioRoute: ImplanteDentarioRoute,
  LimpezaDentalRoute: LimpezaDentalRoute,
  OdontopediatriaRoute: OdontopediatriaRoute,
  OrtodontiaRoute: OrtodontiaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ProteseDentariaRoute: ProteseDentariaRoute,
  RestauracaoDentariaRoute: RestauracaoDentariaRoute,
  RhRoute: RhRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
  CarreirasSlugRoute: CarreirasSlugRoute,
  TratamentosSlugRoute: TratamentosSlugRoute,
  CarreirasIndexRoute: CarreirasIndexRoute,
  ApiCrcInstalarRoute: ApiCrcInstalarRoute,
  ApiCrcLeadRoute: ApiCrcLeadRoute,
  ApiCrcMcpRoute: ApiCrcMcpRoute,
  ApiCrcMotorRoute: ApiCrcMotorRoute,
  ApiCrcSaudeRoute: ApiCrcSaudeRoute,
  ApiCrcWhatsappRoute: ApiCrcWhatsappRoute,
  ApiRhVarrerRoute: ApiRhVarrerRoute,
  ApiRhCurriculoIdRoute: ApiRhCurriculoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
